"""
JSON to IDS XML Converter

将 Pipeline 输出的 JSON 转换为符合 IDS XSD Schema 的 XML 文件。

核心功能:
1. 严格遵循 JSON_TO_IDS_MAPPING.md 中的映射规则
2. 使用 lxml 库构建 XML 树
3. 使用 XSD Schema 进行实时校验
4. 提供详细的错误信息

作者: IDS-Agent
版本: 1.0.0
"""

import json
from datetime import date
from typing import Any, Dict, List, Optional, Union
from pathlib import Path

from lxml import etree
from lxml.etree import XMLSyntaxError


# =============================================================================
# 自定义异常
# =============================================================================

class IDSConversionError(Exception):
    """IDS 转换错误基类"""
    pass


class XSDValidationError(IDSConversionError):
    """XSD 校验失败错误"""

    def __init__(self, message: str, errors: list):
        self.message = message
        self.errors = errors
        super().__init__(self._format_message())

    def _format_message(self) -> str:
        error_details = "\n".join([
            f"  - Line {e.line}: {e.message}" if hasattr(e, 'line') else f"  - {e}"
            for e in self.errors
        ])
        return f"{self.message}\n\nXSD Validation Errors:\n{error_details}"


# =============================================================================
# 命名空间定义
# =============================================================================

NAMESPACES = {
    'ids': 'http://standards.buildingsmart.org/IDS',
    'xs': 'http://www.w3.org/2001/XMLSchema',
    'xsi': 'http://www.w3.org/2001/XMLSchema-instance',
}

NSMAP = {
    'ids': NAMESPACES['ids'],
    'xs': NAMESPACES['xs'],
    'xsi': NAMESPACES['xsi'],
}


# =============================================================================
# 核心转换类
# =============================================================================

class IDSToXMLConverter:
    """
    JSON 到 IDS XML 的转换器

    严格遵循 JSON_TO_IDS_MAPPING.md 中定义的映射规则
    """

    def __init__(self, xsd_path: Optional[str] = None):
        """
        初始化转换器

        Args:
            xsd_path: XSD Schema 文件路径，默认为当前目录下的 ids.xsd
        """
        if xsd_path is None:
            xsd_path = Path(__file__).parent / "ids.xsd"

        self.xsd_path = Path(xsd_path)
        self._schema = None

    def _load_schema(self) -> etree.XMLSchema:
        """加载并缓存 XSD Schema"""
        if self._schema is None:
            if not self.xsd_path.exists():
                raise FileNotFoundError(f"XSD Schema file not found: {self.xsd_path}")

            with open(self.xsd_path, 'rb') as f:
                schema_doc = etree.parse(f)

            self._schema = etree.XMLSchema(schema_doc)

        return self._schema

    def convert(
        self,
        json_data: Dict[str, Any],
        title: Optional[str] = None,
        copyright: str = "Generated by IDS-Agent",
        version: str = "1.0",
        author: Optional[str] = None,
        date_str: Optional[str] = None,
    ) -> str:
        """
        将 JSON 数据转换为 IDS XML 字符串

        Args:
            json_data: Pipeline 输出的 JSON 字典
            title: 可选标题，默认使用第一个 specification 的 name
            copyright: 版权信息
            version: 版本号
            author: 作者邮箱
            date_str: 日期字符串，默认为当前日期

        Returns:
            格式化的 IDS XML 字符串

        Raises:
            XSDValidationError: XSD 校验失败
            IDSConversionError: 其他转换错误
        """
        try:
            # 1. 构建 XML 树
            root = self._build_xml_tree(
                json_data,
                title=title,
                copyright=copyright,
                version=version,
                author=author,
                date_str=date_str,
            )

            # 2. XSD 校验
            schema = self._load_schema()
            if not schema.validate(root):
                errors = schema.error_log
                raise XSDValidationError(
                    "Generated XML does not conform to IDS XSD Schema",
                    list(errors)
                )

            # 3. 格式化输出
            return self._prettify(root)

        except XSDValidationError:
            raise
        except Exception as e:
            raise IDSConversionError(f"Failed to convert JSON to IDS XML: {str(e)}") from e

    def _build_xml_tree(
        self,
        json_data: Dict[str, Any],
        title: Optional[str] = None,
        copyright: str = "Generated by IDS-Agent",
        version: str = "1.0",
        author: Optional[str] = None,
        date_str: Optional[str] = None,
    ) -> etree._Element:
        """
        构建 XML 树

        Args:
            json_data: 输入的 JSON 数据
            title: 标题
            copyright: 版权
            version: 版本
            author: 作者
            date_str: 日期

        Returns:
            lxml Element 对象
        """
        # 创建根节点
        root = etree.Element(
            f"{{{NAMESPACES['ids']}}}ids",
            nsmap=NSMAP
        )

        # 添加 schemaLocation 属性
        root.set(
            f"{{{NAMESPACES['xsi']}}}schemaLocation",
            f"{NAMESPACES['ids']} http://standards.buildingsmart.org/IDS/1.0/ids.xsd"
        )

        # 构建 info 节点
        specs = json_data.get("specifications", [])
        if title is None and specs:
            title = specs[0].get("name", "IDS Specification")

        self._build_info_node(
            root,
            title=title or "IDS Specification",
            copyright=copyright,
            version=version,
            author=author,
            date_str=date_str,
        )

        # 构建 specifications 节点
        self._build_specifications_node(root, specs)

        return root

    def _build_info_node(
        self,
        parent: etree._Element,
        title: str,
        copyright: str,
        version: str,
        author: Optional[str],
        date_str: Optional[str],
    ):
        """
        构建 <ids:info> 节点

        Args:
            parent: 父节点
            title: 标题 (必填)
            copyright: 版权 (可选)
            version: 版本 (可选)
            author: 作者邮箱 (可选)
            date_str: 日期 (可选)
        """
        info = etree.SubElement(parent, f"{{{NAMESPACES['ids']}}}info")

        # title - 必填
        title_elem = etree.SubElement(info, f"{{{NAMESPACES['ids']}}}title")
        title_elem.text = title

        # copyright - 可选
        if copyright:
            copyright_elem = etree.SubElement(info, f"{{{NAMESPACES['ids']}}}copyright")
            copyright_elem.text = copyright

        # version - 可选
        if version:
            version_elem = etree.SubElement(info, f"{{{NAMESPACES['ids']}}}version")
            version_elem.text = version

        # date - 可选，默认当前日期
        if date_str is None:
            date_str = date.today().isoformat()
        date_elem = etree.SubElement(info, f"{{{NAMESPACES['ids']}}}date")
        date_elem.text = date_str

        # author - 可选
        if author:
            author_elem = etree.SubElement(info, f"{{{NAMESPACES['ids']}}}author")
            author_elem.text = author

    def _build_specifications_node(
        self,
        parent: etree._Element,
        specifications: List[Dict[str, Any]]
    ):
        """
        构建 <ids:specifications> 节点

        Args:
            parent: 父节点
            specifications: specification 列表
        """
        specs_node = etree.SubElement(parent, f"{{{NAMESPACES['ids']}}}specifications")

        for spec in specifications:
            self._build_specification_node(specs_node, spec)

    def _build_specification_node(
        self,
        parent: etree._Element,
        spec: Dict[str, Any]
    ):
        """
        构建 <ids:specification> 节点

        Args:
            parent: 父节点
            spec: specification 数据
        """
        spec_elem = etree.SubElement(parent, f"{{{NAMESPACES['ids']}}}specification")

        # name - 必填属性
        spec_elem.set("name", spec.get("name", "Unnamed Specification"))

        # ifcVersion - 必填属性
        ifc_versions = spec.get("ifcVersion", ["IFC4"])
        if isinstance(ifc_versions, list):
            ifc_version_str = " ".join(ifc_versions)
        else:
            ifc_version_str = str(ifc_versions)
        spec_elem.set("ifcVersion", ifc_version_str)

        # description - 可选属性
        if spec.get("description"):
            spec_elem.set("description", spec["description"])

        # instructions - 可选属性
        if spec.get("instructions"):
            spec_elem.set("instructions", spec["instructions"])

        # identifier - 可选属性 (JSON 中通常没有)
        if spec.get("identifier"):
            spec_elem.set("identifier", spec["identifier"])

        # applicability - 必填节点
        applicability = spec.get("applicability", {})
        self._build_applicability_node(spec_elem, applicability)

        # requirements - 可选节点
        requirements = spec.get("requirements")
        if requirements:
            self._build_requirements_node(spec_elem, requirements)

    def _build_applicability_node(
        self,
        parent: etree._Element,
        applicability: Dict[str, Any]
    ):
        """
        构建 <ids:applicability> 节点

        Args:
            parent: 父节点
            applicability: applicability 数据
        """
        app_elem = etree.SubElement(parent, f"{{{NAMESPACES['ids']}}}applicability")

        # minOccurs - 可选属性，默认 "1"
        minOccurs = applicability.get("minOccurs", "1")
        if minOccurs:
            app_elem.set("minOccurs", str(minOccurs))

        # maxOccurs - 可选属性，默认 "unbounded"
        maxOccurs = applicability.get("maxOccurs", "unbounded")
        if maxOccurs:
            app_elem.set("maxOccurs", str(maxOccurs))

        # entity - 可选节点
        entity = applicability.get("entity")
        if entity:
            self._build_entity_node(app_elem, entity)

        # partOf - 可选，多个
        part_of_list = applicability.get("partOf")
        if part_of_list:
            if isinstance(part_of_list, list):
                for part_of in part_of_list:
                    if part_of:
                        self._build_partof_node(app_elem, part_of, is_applicability=True)
            elif isinstance(part_of_list, dict):
                self._build_partof_node(app_elem, part_of_list, is_applicability=True)

        # classification - 可选，多个
        classifications = applicability.get("classification")
        if classifications:
            if isinstance(classifications, list):
                for classification in classifications:
                    if classification:
                        self._build_classification_node(app_elem, classification, is_requirement=False)

        # attribute - 可选，多个
        attributes = applicability.get("attribute")
        if attributes:
            if isinstance(attributes, list):
                for attr in attributes:
                    if attr:
                        self._build_attribute_node(app_elem, attr, is_requirement=False)

        # property - 可选，多个
        properties = applicability.get("property")
        if properties:
            if isinstance(properties, list):
                for prop in properties:
                    if prop:
                        self._build_property_node(app_elem, prop, is_requirement=False)

        # material - 可选，多个
        materials = applicability.get("material")
        if materials:
            if isinstance(materials, list):
                for material in materials:
                    if material:
                        self._build_material_node(app_elem, material, is_requirement=False)

    def _build_requirements_node(
        self,
        parent: etree._Element,
        requirements: Dict[str, Any]
    ):
        """
        构建 <ids:requirements> 节点

        Args:
            parent: 父节点
            requirements: requirements 数据
        """
        req_elem = etree.SubElement(parent, f"{{{NAMESPACES['ids']}}}requirements")

        # description - 可选属性
        if requirements.get("description"):
            req_elem.set("description", requirements["description"])

        # entity - 可选
        entity = requirements.get("entity")
        if entity:
            self._build_entity_node(req_elem, entity, is_requirement=True)

        # partOf - 可选，多个
        part_of_list = requirements.get("partOf")
        if part_of_list:
            if isinstance(part_of_list, list):
                for part_of in part_of_list:
                    if part_of:
                        self._build_partof_node(req_elem, part_of, is_applicability=False)

        # classification - 可选，多个
        classifications = requirements.get("classification")
        if classifications:
            if isinstance(classifications, list):
                for classification in classifications:
                    if classification:
                        self._build_classification_node(req_elem, classification, is_requirement=True)

        # attribute - 可选，多个
        attributes = requirements.get("attribute")
        if attributes:
            if isinstance(attributes, list):
                for attr in attributes:
                    if attr:
                        self._build_attribute_node(req_elem, attr, is_requirement=True)

        # property - 可选，多个
        properties = requirements.get("property")
        if properties:
            if isinstance(properties, list):
                for prop in properties:
                    if prop:
                        self._build_property_node(req_elem, prop, is_requirement=True)

        # material - 可选，多个
        materials = requirements.get("material")
        if materials:
            if isinstance(materials, list):
                for material in materials:
                    if material:
                        self._build_material_node(req_elem, material, is_requirement=True)

    def _build_entity_node(
        self,
        parent: etree._Element,
        entity: Dict[str, Any],
        is_requirement: bool = False
    ):
        """
        构建 <ids:entity> 节点

        Args:
            parent: 父节点
            entity: entity 数据
            is_requirement: 是否在 requirements 中
        """
        entity_elem = etree.SubElement(parent, f"{{{NAMESPACES['ids']}}}entity")

        # name - 必填
        name = entity.get("name")
        if name:
            name_elem = etree.SubElement(entity_elem, f"{{{NAMESPACES['ids']}}}name")
            self._build_ids_value(name_elem, name, uppercase=True)

        # predefinedType - 可选
        predefined_type = entity.get("predefinedType")
        if predefined_type:
            predefined_elem = etree.SubElement(
                entity_elem,
                f"{{{NAMESPACES['ids']}}}predefinedType"
            )
            self._build_ids_value(predefined_elem, predefined_type, uppercase=True)

        # requirements 中 entity 可能有 instructions 属性
        if is_requirement and entity.get("instructions"):
            entity_elem.set("instructions", entity["instructions"])

    def _build_ids_value(
        self,
        parent: etree._Element,
        value: Union[str, Dict[str, Any], None],
        uppercase: bool = False
    ):
        """
        构建 idsValue 类型的节点

        idsValue 是一个选择类型：
        - simpleValue: 简单字符串
        - xs:restriction: 复杂约束

        Args:
            parent: 父节点
            value: 值，可以是字符串或字典
            uppercase: 是否转大写 (用于 entity name)
        """
        if value is None:
            # 输出空的 simpleValue
            simple_elem = etree.SubElement(parent, f"{{{NAMESPACES['ids']}}}simpleValue")
            simple_elem.text = ""
            return

        if isinstance(value, str):
            # 简单字符串 -> simpleValue
            simple_elem = etree.SubElement(parent, f"{{{NAMESPACES['ids']}}}simpleValue")
            text = value.upper() if uppercase else value
            simple_elem.text = text
            return

        if isinstance(value, dict):
            # 字典 -> 检查是否有 restriction
            simple_value = value.get("simpleValue")
            restriction = value.get("restriction")

            if restriction and isinstance(restriction, dict) and self._has_valid_restriction(restriction):
                # 有有效的 restriction -> 输出 xs:restriction
                self._build_restriction_node(parent, restriction)
            else:
                # 没有有效的 restriction -> 输出 simpleValue
                simple_elem = etree.SubElement(parent, f"{{{NAMESPACES['ids']}}}simpleValue")
                if simple_value:
                    text = str(simple_value).upper() if uppercase else str(simple_value)
                    simple_elem.text = text
                else:
                    simple_elem.text = ""
            return

        # 其他类型，转为字符串
        simple_elem = etree.SubElement(parent, f"{{{NAMESPACES['ids']}}}simpleValue")
        simple_elem.text = str(value)

    def _has_valid_restriction(self, restriction: Dict[str, Any]) -> bool:
        """
        检查 restriction 是否有效

        Args:
            restriction: restriction 字典

        Returns:
            是否包含有效的约束条件
        """
        if not restriction:
            return False

        # 检查是否有有效的约束键
        valid_keys = [
            'enumeration', 'pattern', 'minInclusive', 'maxInclusive',
            'minExclusive', 'maxExclusive', 'minLength', 'maxLength',
            'totalDigits', 'fractionDigits', 'whiteSpace', 'length'
        ]

        for key in valid_keys:
            if key in restriction and restriction[key] is not None:
                # enumeration 需要非空列表
                if key == 'enumeration':
                    if isinstance(restriction[key], list) and len(restriction[key]) > 0:
                        return True
                else:
                    return True

        return False

    def _build_restriction_node(
        self,
        parent: etree._Element,
        restriction: Dict[str, Any]
    ):
        """
        构建 <xs:restriction> 节点

        Args:
            parent: 父节点
            restriction: restriction 数据
        """
        # 确定 base 类型
        base = restriction.get("base", "string")
        base_type = f"xs:{base}"

        restriction_elem = etree.SubElement(
            parent,
            f"{{{NAMESPACES['xs']}}}restriction",
            base=base_type
        )

        # 处理 enumeration
        enumeration = restriction.get("enumeration")
        if enumeration and isinstance(enumeration, list):
            for enum_value in enumeration:
                enum_elem = etree.SubElement(
                    restriction_elem,
                    f"{{{NAMESPACES['xs']}}}enumeration",
                    value=str(enum_value)
                )

        # 处理 pattern
        pattern = restriction.get("pattern")
        if pattern:
            pattern_elem = etree.SubElement(
                restriction_elem,
                f"{{{NAMESPACES['xs']}}}pattern",
                value=str(pattern)
            )

        # 处理 minInclusive
        min_inclusive = restriction.get("minInclusive")
        if min_inclusive is not None:
            etree.SubElement(
                restriction_elem,
                f"{{{NAMESPACES['xs']}}}minInclusive",
                value=str(min_inclusive)
            )

        # 处理 maxInclusive
        max_inclusive = restriction.get("maxInclusive")
        if max_inclusive is not None:
            etree.SubElement(
                restriction_elem,
                f"{{{NAMESPACES['xs']}}}maxInclusive",
                value=str(max_inclusive)
            )

        # 处理 minExclusive
        min_exclusive = restriction.get("minExclusive")
        if min_exclusive is not None:
            etree.SubElement(
                restriction_elem,
                f"{{{NAMESPACES['xs']}}}minExclusive",
                value=str(min_exclusive)
            )

        # 处理 maxExclusive
        max_exclusive = restriction.get("maxExclusive")
        if max_exclusive is not None:
            etree.SubElement(
                restriction_elem,
                f"{{{NAMESPACES['xs']}}}maxExclusive",
                value=str(max_exclusive)
            )

        # 处理 minLength
        min_length = restriction.get("minLength")
        if min_length is not None:
            etree.SubElement(
                restriction_elem,
                f"{{{NAMESPACES['xs']}}}minLength",
                value=str(min_length)
            )

        # 处理 maxLength
        max_length = restriction.get("maxLength")
        if max_length is not None:
            etree.SubElement(
                restriction_elem,
                f"{{{NAMESPACES['xs']}}}maxLength",
                value=str(max_length)
            )

        # 处理 length
        length = restriction.get("length")
        if length is not None:
            etree.SubElement(
                restriction_elem,
                f"{{{NAMESPACES['xs']}}}length",
                value=str(length)
            )

    def _build_property_node(
        self,
        parent: etree._Element,
        prop: Dict[str, Any],
        is_requirement: bool = True
    ):
        """
        构建 <ids:property> 节点

        Args:
            parent: 父节点
            prop: property 数据
            is_requirement: 是否在 requirements 中
        """
        prop_elem = etree.SubElement(parent, f"{{{NAMESPACES['ids']}}}property")

        # dataType - 可选属性
        data_type = prop.get("dataType")
        if data_type:
            # 转为大写
            prop_elem.set("dataType", str(data_type).upper())

        # requirements 中的额外属性
        if is_requirement:
            # uri - 可选
            if prop.get("uri"):
                prop_elem.set("uri", prop["uri"])

            # cardinality - 可选，默认 required
            cardinality = prop.get("cardinality", "required")
            if cardinality:
                prop_elem.set("cardinality", cardinality)

            # instructions - 可选
            if prop.get("instructions"):
                prop_elem.set("instructions", prop["instructions"])

        # propertySet - 必填
        property_set = prop.get("propertySet")
        if property_set:
            pset_elem = etree.SubElement(prop_elem, f"{{{NAMESPACES['ids']}}}propertySet")
            self._build_ids_value(pset_elem, property_set)

        # baseName - 必填
        base_name = prop.get("baseName")
        if base_name:
            base_name_elem = etree.SubElement(prop_elem, f"{{{NAMESPACES['ids']}}}baseName")
            self._build_ids_value(base_name_elem, base_name)

        # value - 可选
        value = prop.get("value")
        if value:
            value_elem = etree.SubElement(prop_elem, f"{{{NAMESPACES['ids']}}}value")
            self._build_ids_value(value_elem, value)

    def _build_attribute_node(
        self,
        parent: etree._Element,
        attr: Dict[str, Any],
        is_requirement: bool = True
    ):
        """
        构建 <ids:attribute> 节点

        Args:
            parent: 父节点
            attr: attribute 数据
            is_requirement: 是否在 requirements 中
        """
        attr_elem = etree.SubElement(parent, f"{{{NAMESPACES['ids']}}}attribute")

        # requirements 中的额外属性
        if is_requirement:
            # cardinality - 可选
            cardinality = attr.get("cardinality", "required")
            if cardinality:
                attr_elem.set("cardinality", cardinality)

            # instructions - 可选
            if attr.get("instructions"):
                attr_elem.set("instructions", attr["instructions"])

        # name - 必填
        name = attr.get("name")
        if name:
            name_elem = etree.SubElement(attr_elem, f"{{{NAMESPACES['ids']}}}name")
            self._build_ids_value(name_elem, name)

        # value - 可选
        value = attr.get("value")
        if value:
            value_elem = etree.SubElement(attr_elem, f"{{{NAMESPACES['ids']}}}value")
            self._build_ids_value(value_elem, value)

    def _build_material_node(
        self,
        parent: etree._Element,
        material: Dict[str, Any],
        is_requirement: bool = True
    ):
        """
        构建 <ids:material> 节点

        Args:
            parent: 父节点
            material: material 数据
            is_requirement: 是否在 requirements 中
        """
        mat_elem = etree.SubElement(parent, f"{{{NAMESPACES['ids']}}}material")

        # requirements 中的额外属性
        if is_requirement:
            # uri - 可选
            if material.get("uri"):
                mat_elem.set("uri", material["uri"])

            # cardinality - 可选
            cardinality = material.get("cardinality", "required")
            if cardinality:
                mat_elem.set("cardinality", cardinality)

            # instructions - 可选
            if material.get("instructions"):
                mat_elem.set("instructions", material["instructions"])

        # value - 可选
        value = material.get("value")
        if value:
            value_elem = etree.SubElement(mat_elem, f"{{{NAMESPACES['ids']}}}value")
            self._build_ids_value(value_elem, value)

    def _build_classification_node(
        self,
        parent: etree._Element,
        classification: Dict[str, Any],
        is_requirement: bool = True
    ):
        """
        构建 <ids:classification> 节点

        Args:
            parent: 父节点
            classification: classification 数据
            is_requirement: 是否在 requirements 中
        """
        class_elem = etree.SubElement(parent, f"{{{NAMESPACES['ids']}}}classification")

        # requirements 中的额外属性
        if is_requirement:
            # uri - 可选
            if classification.get("uri"):
                class_elem.set("uri", classification["uri"])

            # cardinality - 可选
            cardinality = classification.get("cardinality", "required")
            if cardinality:
                class_elem.set("cardinality", cardinality)

            # instructions - 可选
            if classification.get("instructions"):
                class_elem.set("instructions", classification["instructions"])

        # system - 必填
        system = classification.get("system")
        if system:
            system_elem = etree.SubElement(class_elem, f"{{{NAMESPACES['ids']}}}system")
            self._build_ids_value(system_elem, system)

        # value - 可选
        value = classification.get("value")
        if value:
            value_elem = etree.SubElement(class_elem, f"{{{NAMESPACES['ids']}}}value")
            self._build_ids_value(value_elem, value)

    def _build_partof_node(
        self,
        parent: etree._Element,
        part_of: Dict[str, Any],
        is_applicability: bool = True
    ):
        """
        构建 <ids:partOf> 节点

        Args:
            parent: 父节点
            part_of: partOf 数据
            is_applicability: 是否在 applicability 中
        """
        partof_elem = etree.SubElement(parent, f"{{{NAMESPACES['ids']}}}partOf")

        # relation - 可选属性
        relation = part_of.get("relation")
        if relation:
            partof_elem.set("relation", str(relation).upper())

        # requirements 中的额外属性
        if not is_applicability:
            # cardinality - 可选
            cardinality = part_of.get("cardinality", "required")
            if cardinality:
                partof_elem.set("cardinality", cardinality)

            # instructions - 可选
            if part_of.get("instructions"):
                partof_elem.set("instructions", part_of["instructions"])

        # entity - 必填
        entity = part_of.get("entity")
        if entity:
            self._build_entity_node(partof_elem, entity)

    def _prettify(self, root: etree._Element) -> str:
        """
        格式化 XML 输出

        Args:
            root: XML 根节点

        Returns:
            格式化的 XML 字符串
        """
        # 添加 XML 声明
        xml_declaration = b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'

        # 格式化
        pretty_xml = etree.tostring(
            root,
            pretty_print=True,
            encoding='UTF-8',
            xml_declaration=False
        )

        return (xml_declaration + pretty_xml).decode('UTF-8')


# =============================================================================
# 便捷函数
# =============================================================================

def convert_json_to_ids_xml(
    json_data: Dict[str, Any],
    xsd_path: Optional[str] = None,
    **kwargs
) -> str:
    """
    将 JSON 数据转换为 IDS XML 字符串

    Args:
        json_data: Pipeline 输出的 JSON 字典
        xsd_path: 可选的 XSD 文件路径
        **kwargs: 传递给 IDSToXMLConverter.convert 的额外参数
            - title: 标题
            - copyright: 版权信息
            - version: 版本号
            - author: 作者邮箱
            - date_str: 日期字符串

    Returns:
        格式化的 IDS XML 字符串

    Raises:
        XSDValidationError: XSD 校验失败
        IDSConversionError: 其他转换错误

    Example:
        >>> json_data = {"specifications": [...]}
        >>> xml_str = convert_json_to_ids_xml(json_data)
        >>> print(xml_str)
    """
    converter = IDSToXMLConverter(xsd_path=xsd_path)
    return converter.convert(json_data, **kwargs)


def convert_json_file_to_ids_xml(
    json_path: str,
    output_path: Optional[str] = None,
    xsd_path: Optional[str] = None,
    **kwargs
) -> str:
    """
    将 JSON 文件转换为 IDS XML 文件

    Args:
        json_path: 输入 JSON 文件路径
        output_path: 输出 XML 文件路径（可选，不提供则返回字符串）
        xsd_path: 可选的 XSD 文件路径
        **kwargs: 传递给 convert_json_to_ids_xml 的额外参数

    Returns:
        格式化的 IDS XML 字符串

    Raises:
        FileNotFoundError: JSON 文件不存在
        XSDValidationError: XSD 校验失败
        IDSConversionError: 其他转换错误
    """
    # 读取 JSON 文件
    with open(json_path, 'r', encoding='utf-8') as f:
        json_data = json.load(f)

    # 转换
    xml_str = convert_json_to_ids_xml(json_data, xsd_path=xsd_path, **kwargs)

    # 保存到文件
    if output_path:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(xml_str)

    return xml_str


# =============================================================================
# 测试入口
# =============================================================================

if __name__ == "__main__":
    import sys

    # 测试文件路径
    current_dir = Path(__file__).parent
    json_file = current_dir / "pipeline_result_1.json"
    xsd_file = current_dir / "ids.xsd"
    output_file = current_dir / "output.ids"

    print("=" * 60)
    print("IDS JSON to XML Converter Test")
    print("=" * 60)
    print()

    # 检查文件是否存在
    if not json_file.exists():
        print(f"❌ Error: JSON file not found: {json_file}")
        sys.exit(1)

    if not xsd_file.exists():
        print(f"❌ Error: XSD file not found: {xsd_file}")
        sys.exit(1)

    print(f"📂 Input JSON: {json_file}")
    print(f"📂 XSD Schema: {xsd_file}")
    print(f"📂 Output XML: {output_file}")
    print()

    try:
        # 读取 JSON
        print("📖 Reading JSON file...")
        with open(json_file, 'r', encoding='utf-8') as f:
            json_data = json.load(f)

        print(f"   Found {len(json_data.get('specifications', []))} specification(s)")
        print()

        # 转换
        print("🔄 Converting JSON to IDS XML...")
        converter = IDSToXMLConverter(xsd_path=str(xsd_file))
        xml_result = converter.convert(
            json_data,
            title=None,  # 使用第一个 specification 的 name
            copyright="Generated by IDS-Agent",
            version="1.0",
        )

        print("✅ Conversion successful!")
        print()

        # 保存输出
        print("💾 Saving output...")
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(xml_result)

        print(f"   Output saved to: {output_file}")
        print()

        # 打印 XML
        print("=" * 60)
        print("Generated IDS XML:")
        print("=" * 60)
        print()
        print(xml_result)
        print()

        # 验证输出
        print("=" * 60)
        print("Validation Result:")
        print("=" * 60)
        print("✅ XSD validation passed")
        print("✅ XML is well-formed")
        print()

    except XSDValidationError as e:
        print("=" * 60)
        print("❌ XSD Validation Failed!")
        print("=" * 60)
        print()
        print(str(e))
        print()
        sys.exit(1)

    except IDSConversionError as e:
        print("=" * 60)
        print("❌ Conversion Error!")
        print("=" * 60)
        print()
        print(str(e))
        print()
        sys.exit(1)

    except Exception as e:
        print("=" * 60)
        print("❌ Unexpected Error!")
        print("=" * 60)
        print()
        print(str(e))
        print()
        import traceback
        traceback.print_exc()
        sys.exit(1)
