import json
import os
import subprocess
import sys
from pathlib import Path

import pytest
from lxml import etree

from ids_converter.converter import IDSToXMLConverter, convert_json_to_ids_xml


FIXTURE_DIR = Path(__file__).parent / "test_ids_json"
XSD_PATH = Path(__file__).parent / "ids.xsd"


def test_converter_loads_ids_xsd_schema():
    result = subprocess.run(
        [
            sys.executable,
            "-c",
            (
                "from ids_converter.converter import IDSToXMLConverter; "
                f"IDSToXMLConverter(r'{XSD_PATH}')._load_schema(); "
                "print('schema ok')"
            ),
        ],
        cwd=Path(__file__).parents[1],
        env={
            "PATH": os.environ["PATH"],
            "PYTHONPATH": str(Path(__file__).parents[1]),
        },
        text=True,
        capture_output=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr


@pytest.mark.parametrize(
    "fixture_name",
    [
        "pipeline_result_1.json",
        "pipeline_result_2.json",
    ],
)
def test_json_fixtures_convert_to_xsd_valid_ids_xml(fixture_name):
    with (FIXTURE_DIR / fixture_name).open("r", encoding="utf-8") as fixture:
        json_data = json.load(fixture)

    ids_xml = convert_json_to_ids_xml(
        json_data,
        xsd_path=str(XSD_PATH),
        title=f"Test Specification - {fixture_name}",
        copyright="Generated by IDS-Agent Pipeline",
        version="1.0",
        date_str="2026-03-19",
    )

    etree.fromstring(ids_xml.encode("utf-8"))
    assert "<xs:restriction" in ids_xml
