"""
完整流程测试：自然语言 -> IDS -> IFC验证

测试用例：Girders桥梁主梁规范
"""
import asyncio
import json
import sys
from pathlib import Path

# 添加路径
sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent.parent / "ids_converter"))
sys.path.insert(0, str(Path(__file__).parent.parent / "ifc_checker"))

from pipeline import run_ids_pipeline
from converter import convert_json_to_ids_xml
from checker_service import check_ifc_against_ids


async def test_full_workflow():
    """完整流程测试"""

    print("="*80)
    print("完整流程测试：自然语言 -> IDS -> IFC验证")
    print("="*80)

    # 步骤1：自然语言规范
    input_file = Path("test_input/deck_spec.txt")
    spec_text = input_file.read_text(encoding="utf-8")

    print("\n[步骤1] 自然语言规范:")
    print(spec_text)

    # 步骤2：生成IDS JSON
    print("\n[步骤2] 运行Pipeline生成IDS...")
    ids_json, timing, stage_outputs = await run_ids_pipeline(
        spec_text,
        return_timing=True,
        return_stage_outputs=True
    )

    print(f"  生成的规范数量: {len(ids_json.get('specifications', []))}")
    print(f"  IFC版本: {ids_json.get('metadata', {}).get('ifc_version')}")

    # 保存各阶段输出
    print("\n[步骤2.1] 保存各阶段输出...")
    stages_dir = Path("test_output/deck_stages")
    stages_dir.mkdir(parents=True, exist_ok=True)

    for stage_name, stage_data in stage_outputs.items():
        stage_file = stages_dir / f"{stage_name}.json"
        with open(stage_file, 'w', encoding='utf-8') as f:
            json.dump(stage_data, f, indent=2, ensure_ascii=False)
        print(f"  [OK] {stage_name} 已保存: {stage_file}")

    # 保存耗时信息
    timing_file = stages_dir / "timing.json"
    with open(timing_file, 'w', encoding='utf-8') as f:
        json.dump(timing, f, indent=2, ensure_ascii=False)
    print(f"  [OK] 耗时信息已保存: {timing_file}")

    # 保存JSON
    json_path = Path("test_output/deck_spec.json")
    json_path.parent.mkdir(exist_ok=True)
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(ids_json, f, indent=2, ensure_ascii=False)
    print(f"  JSON已保存: {json_path}")

    # 步骤3：转换为IDS XML
    print("\n[步骤3] 转换为IDS XML...")
    try:
        ids_xml = convert_json_to_ids_xml(
            ids_json,
            xsd_path=str(Path(__file__).parent.parent / "ids_converter" / "ids.xsd"),
            title="Deck Bridge Specification",
            copyright="Generated by IDS-Agent"
        )

        xml_path = Path("test_output/deck_spec.ids")
        with open(xml_path, 'w', encoding='utf-8') as f:
            f.write(ids_xml)
        print(f"  IDS XML已保存: {xml_path}")
        print(f"  XML长度: {len(ids_xml)} 字符")

    except Exception as e:
        print(f"  ❌ XML转换失败: {e}")
        return False

    # 步骤4：验证IFC文件
    print("\n[步骤4] 验证IFC文件...")
    ifc_path = Path("test_bridge_girder.ifc")

    if not ifc_path.exists():
        print(f"  ⚠️  IFC文件不存在: {ifc_path}")
        print("  请先创建测试IFC文件")
        return False

    try:
        result = check_ifc_against_ids(
            ids_file_path=str(xml_path),
            ifc_file_path=str(ifc_path),
            output_dir="test_output/checker_report"
        )

        print(f"\n{'='*80}")
        print("验证结果")
        print(f"{'='*80}")
        print(f"状态: {'✅ 成功' if result['success'] else '❌ 失败'}")
        print(f"消息: {result['message']}")
        print(f"\n摘要:")
        print(f"  总规格数: {result['summary']['total_specs']}")
        print(f"  通过: {result['summary']['passed_specs']}")
        print(f"  失败: {result['summary']['failed_specs']}")
        print(f"  失败构件数: {result['summary']['total_failed_entities']}")

        if result.get('html_report_path'):
            print(f"\nHTML报告: {result['html_report_path']}")

        return result['success']

    except Exception as e:
        print(f"  ❌ IFC验证失败: {e}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == "__main__":
    success = asyncio.run(test_full_workflow())

    print(f"\n{'='*80}")
    if success:
        print("✅ 完整流程测试通过！")
    else:
        print("❌ 测试失败，请检查上述错误信息")
    print(f"{'='*80}\n")

    sys.exit(0 if success else 1)
